### ISSUE TITLE
Histogram allows min to be set to greater than max with error

### ISSUE THREAD

**Issue by mcraig-ibme** [ibme-qubic/quantiphyse#14]
Traceback is:

max must be larger than min in range parameter.

Details:
```
Traceback (most recent call last):

File "/home/ibmeuser/ibmecode/build_scripts/build/quantiphyse/dist/quantiphyse/packages/core/histogram/widget.py", line 103, in _update
HistogramProcess(self.ivm).run(opts)
File "/home/ibmeuser/ibmecode/build_scripts/build/quantiphyse/dist/quantiphyse/packages/core/histogram/process.py", line 68, in run
data_vals, edges = np.histogram(region_data, bins=bins, range=hrange, density=prob)
File "site-packages/numpy/lib/histograms.py", line 780, in histogram
File "site-packages/numpy/lib/histograms.py", line 417, in _get_bin_edges
File "site-packages/numpy/lib/histograms.py", line 304, in _get_outer_edges
ValueError: max must be larger than min in range parameter.
```

**Comment by mcraig-ibme** [comment]
Awaiting release

**Comment by mcraig-ibme** [comment]
v0.8
