### ISSUE TITLE
Occasional error in voxel analysis

### ISSUE THREAD

**Issue by mcraig-ibme** [ibme-qubic/quantiphyse#37]
When clicking around an image I occasionally get:

```
'PySide2.QtGui.QStandardItem' object has no attribute 'childItems'

Details:

Traceback (most recent call last):

File "/Users/ctsu0221/.conda/envs/qp/lib/python3.7/site-packages/pyqtgraph/graphicsItems/GraphicsObject.py", line 26, in itemChange
self.parentChanged()

File "/Users/ctsu0221/.conda/envs/qp/lib/python3.7/site-packages/pyqtgraph/graphicsItems/GraphicsItem.py", line 463, in parentChanged
self._updateView()

File "/Users/ctsu0221/.conda/envs/qp/lib/python3.7/site-packages/pyqtgraph/graphicsItems/GraphicsItem.py", line 523, in _updateView
self._replaceView(oldView)

File "/Users/ctsu0221/.conda/envs/qp/lib/python3.7/site-packages/pyqtgraph/graphicsItems/GraphicsItem.py", line 541, in _replaceView
self._replaceView(oldView, child)

File "/Users/ctsu0221/.conda/envs/qp/lib/python3.7/site-packages/pyqtgraph/graphicsItems/GraphicsItem.py", line 535, in _replaceView
for child in item.childItems():

AttributeError: 'PySide2.QtGui.QStandardItem' object has no attribute 'childItems'

```

**Comment by mcraig-ibme** [comment]
Also following error on console

```
    |==============================>>
    |  Traceback (most recent call last):
    |    File "/Users/ctsu0221/.conda/envs/qp/bin/quantiphyse", line 8, in <module>
    |      sys.exit(main())
    |    File "/Users/ctsu0221/.conda/envs/qp/lib/python3.7/site-packages/quantiphyse/qpmain.py", line 154, in main
    |      sys.exit(app.exec_())
    |    File "/Users/ctsu0221/.conda/envs/qp/lib/python3.7/site-packages/pyqtgraph/widgets/GraphicsView.py", line 382, in mouseMoveEvent
    |      QtGui.QGraphicsView.mouseMoveEvent(self, ev)
    |    File "/Users/ctsu0221/.conda/envs/qp/lib/python3.7/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 202, in mouseMoveEvent
    |      self.sendHoverEvents(ev)
    |    File "/Users/ctsu0221/.conda/envs/qp/lib/python3.7/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 304, in sendHoverEvents
    |      debug.printExc("Error sending hover exit event:")
    |    --- exception caught here ---
    |    File "/Users/ctsu0221/.conda/envs/qp/lib/python3.7/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 301, in sendHoverEvents
    |      if item.scene() is self:
    |  RuntimeError: Internal C++ object (ScatterPlotItem) already deleted.
    |==============================<<
[12:50:23]  Error sending hover exit event:
```

**Comment by mcraig-ibme** [comment]
Closing as not occurred recently, probably a Qt/Pyside incompatibility
