### ISSUE TITLE
Quantiphyse Installlation Error

### ISSUE THREAD

**Issue by onurhank** [ibme-qubic/quantiphyse#39]
I have installed the Quantiphyse according to installation guide but when I write "quantiphyse" after activating conda i am getting this error. I searched but I couldn't find a solution.
"Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/envs/qp/bin/quantiphyse", line 5, in <module>
    from quantiphyse.qpmain import main
  File "/Users/user/opt/anaconda3/envs/qp/lib/python3.7/site-packages/quantiphyse/qpmain.py", line 43, in <module>
    from quantiphyse.test import run_tests
  File "/Users/user/opt/anaconda3/envs/qp/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/user/opt/anaconda3/envs/qp/lib/python3.7/site-packages/quantiphyse/test/__init__.py", line 15, in <module>
    from .widget_test import WidgetTest
  File "/Users/user/opt/anaconda3/envs/qp/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/user/opt/anaconda3/envs/qp/lib/python3.7/site-packages/quantiphyse/test/widget_test.py", line 21, in <module>
    from quantiphyse.gui.viewer.viewer import Viewer
  File "/Users/user/opt/anaconda3/envs/qp/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/user/opt/anaconda3/envs/qp/lib/python3.7/site-packages/quantiphyse/gui/viewer/viewer.py", line 35, in <module>
    from .view_params_widget import ViewParamsWidget
  File "/Users/user/opt/anaconda3/envs/qp/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/user/opt/anaconda3/envs/qp/lib/python3.7/site-packages/quantiphyse/gui/viewer/view_params_widget.py", line 33, in <module>
    from quantiphyse.gui.widgets import RoiCombo, OverlayCombo
  File "/Users/user/opt/anaconda3/envs/qp/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/user/opt/anaconda3/envs/qp/lib/python3.7/site-packages/quantiphyse/gui/widgets.py", line 31, in <module>
    from quantiphyse.gui.options import OptionBox, FileOption 
  File "/Users/user/opt/anaconda3/envs/qp/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/user/opt/anaconda3/envs/qp/lib/python3.7/site-packages/quantiphyse/gui/options.py", line 46, in <module>
    from quantiphyse.gui.dialogs import MatrixViewerDialog, ChooseFromListDialog, PlotDialog1d
  File "/Users/user/opt/anaconda3/envs/qp/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/user/opt/anaconda3/envs/qp/lib/python3.7/site-packages/quantiphyse/gui/dialogs.py", line 50, in <module>
    class MultiTextViewerDialog(QtGui.QDialog):
AttributeError: module 'PySide2.QtGui' has no attribute 'QDialog
"

**Comment by michaelburke321** [comment]
Hi,
had similar issues. I was able to solve them by installing 

sudo apt install libqt4-dev qt4-qmake cmake python-dev python-setuptools

on Ubuntu 18.X.

Then pip install quantiphyse –user
and
pip install quantiphyse-cest quantiphyse-asl quantiphyse-cest quantiphyse-dce quantiphyse-dsc quantiphyse-t1 quantiphyse-fsl quantiphyse-sv --user
pip install deprecation==1.2 --user

Due to some issue with fas.data.atlases I deinstalled quantiphyse-fsl (pip uninstall quantiphyse-fsl) and got it up and running (without FSL support so far.

Good luck
Michael

**Comment by mcraig-ibme** [comment]
Hi, sorry I have not been getting notifications on these issues so I have been very slow to respond!

There were various problems of this type caused by the split between QtGui and QtWidgets in QT5. I think all these are now fixed and the current version of Quantiphyse in pip (v0.9.9.post2) should work correctly. Let me know if this is not the case.

**Comment by MinhVo89** [comment]
Dear Author,
I have installed Quantiphyse according to the guideline. Unfortunately, there was an issue: I see you are using Linux
Traceback (most recent call last):
  File "qp_install.py", line 379, in <module>
    main()
  File "qp_install.py", line 35, in main
    install_mac_linux()
  File "qp_install.py", line 145, in install_mac_linux
    print("\nInstallation choices - type number to choose [%i]:" % (recommended+1))
UnboundLocalError: local variable 'recommended' referenced before assignment


Could you kindly help me to solve this issue?

Thanks

**Comment by mcraig-ibme** [comment]
Apologies, the qp_install.py script is unfinished and not likely to work out of the box. I haven't had time to return to this. The installation instructions at quantiphyse.readthedocs.io are the best current guide to installation.

**Comment by mcraig-ibme** [comment]
Leaving open for now will decide whether to remove this script or try to make it work
