### ISSUE TITLE
Python 3.4 failure on startup

### ISSUE THREAD

**Issue by mcraig-ibme** [ibme-qubic/quantiphyse#4]
```
09:33:59 DEBUG quantiphyse.utils.local Local directory: /home/ibmeuser/build/build_scripts/build/quantiphyse/quantiphyse/utils/..
09:33:59 DEBUG quantiphyse.utils.plugins Loading plugins from /home/ibmeuser/build/build_scripts/build/quantiphyse/quantiphyse/packages/plugins
09:33:59 DEBUG quantiphyse.utils.plugins Loading plugins from /home/ibmeuser/build/build_scripts/build/quantiphyse/quantiphyse/packages/core
09:33:59 DEBUG quantiphyse.utils.plugins Trying to import compare
===== 2019.02.06 09:02:59 =====
Traceback (most recent call last):
  File "qp.py", line 10, in <module>
    quantiphyse.qpmain.main()
  File "/home/ibmeuser/build/build_scripts/build/quantiphyse/quantiphyse/qpmain.py", line 104, in main
    win = MainWindow(load_data=args.data, widgets=not args.qv)
  File "/home/ibmeuser/build/build_scripts/build/quantiphyse/quantiphyse/gui/MainWindow.py", line 158, in __init__
    widgets = get_plugins("widgets")
  File "/home/ibmeuser/build/build_scripts/build/quantiphyse/quantiphyse/utils/plugins.py", line 89, in get_plugins
    _load_plugins_from_dir(plugin_dir, "quantiphyse." + pkg, PLUGIN_MANIFEST)
  File "/home/ibmeuser/build/build_scripts/build/quantiphyse/quantiphyse/utils/plugins.py", line 45, in _load_plugins_from_dir
    module = importlib.import_module(mod, pkgname)
  File "/home/ibmeuser/miniconda3/envs/qp3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2249, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2199, in _sanity_check
SystemError: Parent module 'quantiphyse.packages.core' not loaded, cannot perform relative import
```

**Comment by mcraig-ibme** [comment]
This is now fixed on master.

Seems that python 3 has slightly tightened up the rules for importing modules programatically. I've worked around it by making sure the 'parent' module (e.g. quantiphyse.packages.core) is imported before we try to scan it for plugins. In the longer term we want to move to using entry points as the only means of loading plugins (core or additional) so this code will be deprecated in the future.
