### ISSUE TITLE
Error in Fabber T1 widget when data in separate files

### ISSUE THREAD

**Issue by mcraig-ibme** [ibme-qubic/quantiphyse#6]
Occurs whenever the calculation is run with multiple data files (one per VFA). By the look of the traceback this is an issue in quantiphyse rather than the widget code.

```
13:51:48 DEBUG quantiphyse.gui.widgets.RunBox RunBox: Finished: 2 0 'numpy.ndarray' object has no attribute 'nvols'
Traceback (most recent call last):
  File "/home/ibmeuser/build/build_scripts/build/quantiphyse/quantiphyse/processes/process.py", line 194, in execute
    self.run(options)
  File "/home/ibmeuser/build/build_scripts/build/quantiphyse/quantiphyse/packages/plugins/quantiphyse_fabber/process.py", line 114, in run
    data = self.get_data(options, multi=True)
  File "/home/ibmeuser/build/build_scripts/build/quantiphyse/quantiphyse/processes/process.py", line 248, in get_data
    data[..., num_vols:num_vols+data.nvols] = rawdata
AttributeError: 'numpy.ndarray' object has no attribute 'nvols'
```

**Comment by mcraig-ibme** [comment]
Fixed in master. Awaiting release

**Comment by mcraig-ibme** [comment]
0.7.7.post26
